name: Zarifs Demo Action
description: This action greets a person
inputs:
  person:
    description: 'The name of the person to greet'
    required: true
    default: 'Monolisa Octocat'
runs:
  using: node16
  main: dist/index.js # pointing to the bundled file by esbuild
