name: Test

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm run build
      - run: rm -rf node_modules
      - run: npm ci
      - uses: ./ # runs default action
      - uses: ./
        with:
          person: 'Zarif'
